function [sig] = module_signaling(met, par, mutant_type, snf1_vals)

%aa_ex = met(1); 
gl    = met(2); 
pc    = met(3); 
aa_in = met(5); 

% SNF1
if strcmp(mutant_type,'none') ...
|| strcmp(mutant_type,'const_gl') ...
|| strcmp(mutant_type,'const_eh') ...
|| strcmp(mutant_type,'const_gl_eh_aaex_cell') ...
|| strcmp(mutant_type,'const_jgy') ...
|| strcmp(mutant_type,'hxt') ...
|| strcmp(mutant_type,'hap4_overexpress') ...
|| strcmp(mutant_type,'hap4_underexpress')...
|| strcmp(mutant_type,'const_tor') ...
|| strcmp(mutant_type,'const_tor_gl') ...
|| strcmp(mutant_type,'const_tor_eh') ...
|| strcmp(mutant_type,'const_tor_gl_eh_aaex_cell')...
|| strcmp(mutant_type,'const_gl_eh_aaex_cell_hap_over')...
|| strcmp(mutant_type,'const_gl_eh_aaex_cell_hap_under')...
|| strcmp(mutant_type,'addH')... 
|| strcmp(mutant_type,'const_gl_eh_aaex_cell_addH')...
|| strcmp(mutant_type,'low_gn')... 
|| strcmp(mutant_type,'low_mt')...    
|| strcmp(mutant_type,'low_mt_gn')

%sig.snf1 = (par.s_basal + ((1 - par.s_basal) * hill(par.K_s_p2, gl, par.theta_s_p2))) * par.s_tot;
sig.snf1 = (par.s_basal + ((1 - par.s_basal) * hill(par.K_s_pc, pc, par.theta_s_pc))) * par.s_tot;

elseif strcmp(mutant_type,'const_snf1') ...
|| strcmp(mutant_type,'const_snf1_gl') ...
|| strcmp(mutant_type,'const_snf1_eh') ...
|| strcmp(mutant_type,'const_snf1_gl_eh_aaex_cell')

if length(snf1_vals) == 1 || gl > 100
sig.snf1 = snf1_vals(1);
else
sig.snf1 = snf1_vals(2);
end
end 

% TOR 
sig.tor  = (par.tau_basal + ((1 - par.tau_basal) * hill(aa_in, par.K_tau_aai, par.theta_tau_aai))) * par.tau_tot;
%sig.tor  = 0;

if strcmp(mutant_type,'const_tor') ...
|| strcmp(mutant_type,'const_tor_gl') ...
|| strcmp(mutant_type,'const_tor_eh') ...
|| strcmp(mutant_type,'const_tor_gl_eh_aaex_cell')

sig.tor = snf1_vals;

end 

end 
